"""Carrito y Pedidos

Revision ID: 35a116f45ec6
Revises: 2f50ba5c3df3
Create Date: 2026-02-09 14:15:05.496935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a116f45ec6'
down_revision: Union[str, Sequence[str], None] = '2f50ba5c3df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
