"""Columna stock agregada en Producto

Revision ID: e7d42820ef7e
Revises: 7ad96cbdf499
Create Date: 2026-02-10 01:16:56.114013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d42820ef7e'
down_revision: Union[str, Sequence[str], None] = '7ad96cbdf499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'stock')
    # ### end Alembic commands ###
